- src/core/core_i_constants.nss
- src/hooks/hook_area01.nss
- src/hooks/hook_area02.nss
- src/hooks/hook_module03.nss
- src/hooks/hook_module04.nss
We discussed this on discord a few times, but just realized it was never implemented.  Here's the code we discussed, along with a few other minor modifications for rostering/player management.  The modification from our discord discussion allows the Area Roster to be used even if the builder does not allow the OnAreaEmpty event.
* Adds a DM roster, in addition to the Area and Player rosters.
* Adds OnAreaEmpty timer functions
* Adds appropriate constants to make above work.
Feedback welcome.
> OnAreaEmpty

- src/core/core_c_config.nss
- src/core/core_i_constants.nss
- src/core/core_i_framework.nss
- src/hooks/hook_area03.nss
- src/hooks/hook_creature07.nss
- src/hooks/hook_door06.nss
- src/hooks/hook_encounter04.nss
- src/hooks/hook_module06.nss
- src/hooks/hook_placeable05.nss
- src/hooks/hook_trigger04.nss
- src/utils/util_i_csvlists.nss
After a few iterations of this, I discovered that I couldn't really subvert the debug levels independently of temporarily changing the module debug level because of the way the `Debug()` function (and the functions it calls) worked.  To get around that, I added new methodology for a builder to specify object and event debug levels independent of the module level.  Of course, you can still use the original method to get the higher comparative verbosity level.  If you use the new method (`SetObjectDebugLevel()` and/or `SetEventDebugLevel()`), it will use the specific level regardless of the module's level.  As before, this compiles, but was not live-tested.  Also this branch was created from the 1bdced3 commit, so none of the changes from PR #5 are in it, thus restoring util_i_debug to the …
> Debug levels independent of util_i_debug

- src/core/core_i_framework.nss
After some more testing, I narrowed it down to a couple lines of code.  When a timer is stopped, or otherwise not running, but does exist, the error checking in `_TimerElapsed` kills the timer instead of preserving it for future use, which is likely the reason it was created or stopped to begin with.  This change preserves stopped timers, but still allows timers that error out for other reasons to be killed.
I'm sure there's a more graceful way to do this, but I took the brute force flag method.  Also, to prevent inundations of little PRs for the timers, I tested the rest of the functions, but couldn't find any other issues (knock on wood).
> Stopped timers not preserved for future use.

- src/core/core_i_framework.nss
- src/hooks/hook_area02.nss
Finally got around to this.  Went back and forth on how best to implement this and I think it has the most potential use in this form factor.  I opted for `InitializeEvent()` since that had to be accomplished anyway and ensures we we're looking for local events also (might have this logic wrong).  Subsequent runs access the `oEvent` object directly for quicker access times.  Adding the `HasEventScripts` allows for other functions to access it as well as cleaning up the hook script a little.
> area empty event bypass

- src/core/core_i_constants.nss
- src/hooks/hook_module03.nss
`GetWasPC()` referenced a non-existent constant (`IS_PC`).  Added that constand (and `IS_DM` for consistency, even though not currently used) to `core_i_const`.  Added assignment of `IS_DM` and `IS_PC` to `oPC` objects OCE in `hook_module03`.
> Added constants, assignment.

- src/core/core_c_config.nss
- src/core/core_i_constants.nss
- src/hooks/hook_aoe01.nss
- src/hooks/hook_aoe02.nss
- src/hooks/hook_aoe03.nss
This PR adds in hook scripts for AOE events.  When creating an AOE, to allow the framework to manipulate the events, it should be created like this:
```c
effect eAOE = EffectAreaOfEffect(AOE_PER_CUSTOM_AOE, "hook_aoe01", "hook_aoe02", "hook_aoe03");
```
Scripters can then assign global or local scripts as desired, just as with any other events.  AOE hook scripts create "AOE Rosters", just like the framework's DM Roster and Player Roster.  This allows builders to easily loop through all objects in the AOE to provide desired effects.  Including NPCs in the AOE Roster is optional and can be set in `core_i_config`.
`hook_aoe03` allows for an  `AoEOnEmpty` event when the last object departs the AOE.
> add aoe hook scripts

- src/core/core_c_config.nss
- src/core/core_i_framework.nss
Not the most terribly useful addition, but this new setting allows the builder to set a specified debug level during core framework intialization.  The purpose of this is to quiet down the verbosity and server logs, but only until the framework has completed its initialization.  The setting then reverts back to the normal debug setting.
> added framework initialization debug setting

- src/core/core_c_config.nss
- src/core/core_i_framework.nss
Generally this is not an issue in EE, however, in 1.69, initializatin the core-framework can cause TMI very quickly due to the modular nature of scripts and plugins that the framework allows.  This option was added in order to allow the build to run a specific script before the framework initialized.  Specifically, this was designed to allow NWNX2 users to raise thier TMI limit through nwnx_tmi before running into TMI during framework initilializtion, but it can be used for any functions the builder desires.
> added option to run a pre-load script before framework initialization

- src/core/core_i_framework.nss
Added the option to have tag-based scripting for all game objects.  Currently, in the base game and in the framework, tag-based scripting is allowed for items only.  This addition allows for tag-based scripting for all game objects.  The library system is designed to reduce script count and consolidate like functions into single scripts.  This capability extended that idea.  It allows libraries such as this example, specified to areas, that allow builders to consolidate object-specific functions into libraries that otherwise would not have a good place to be included.  In this example, all local area-specific functions can be contained in a single library, which allow builders to easily find and change object-specific functions (vice setting variables) and consolidate excess scripts.  It …
> added tag-based scripting for all game objects

- src/hooks/hook_module08.nss
- src/utils/util_i_chat.nss
This PR introduces `util_i_chat`, which is a chat command system.  This script provides the functions that allow the chat command to used like a command line, including arguments (no prefix dashes), short option (single prefix dash), long options (double prefix dash) and pairs (`-|--key:value` or `-|--key=value`).  It can also accepted grouped characters, designated with any set of grouping character the builder chooses (such as `""`, `{}`, `[]`, etc.).  Any characters within these grouping characters will be returned as a string.  `util_i_csvlists` is used, so commas are not allows (except as a chat-command designator character) and will be stripped during the tokenization process.  Example:
```c
!cmd "This is a group"
```
will return a single argument with the value `This is a group` …
> Utility chat

- src/chat/chat_c_config.nss
- src/chat/chat_i_main.nss
- src/chat/chat_l_plugin.nss
- src/core/core_i_database.nss
- src/demo/_loadlibs.nss
- src/demo/_test.nss
- src/demo/core_c_config.nss
- src/demo/demo_l_plugin.nss
- src/hooks/hook_module08.nss
- src/utils/util_i_chat.nss
This is PR #24 re-implemented as a plugin.
-  Scripts that use `util_i_chat.nss` will want to include `chat_i_main.nss` instead.
- Configuration options are now in `chat_c_config.nss`.
- I have changed a few constant names to avoid possible collision with other libraries (e.g., `GROUPS -> CHAT_GROUPS`), so that may require some edits to existing scripts.
- The demo module now includes a single chat command `!colors` which tests `util_i_colors.nss`.
@tinygiant98 if this works for you, I can merge it in.
> Chat Command Plugin

- src/dialogs/dlg_i_dialogs.nss
Added 2x dialog page parent functions, primarily to allow for page name comparisons of child pages during the page and node events:
`GetDialogPageParent` (string) - Returns the most distant ancestor of the current page, so if it's `MyPage#5`, it'll return `MyPage`
`GetDialogPageNumber` (int) - Returns the numeric portion of the page, if it exists, so for `MyPage#5`, it'll return `5`
> added dialog page parent functions

- src/utils/util_i_libraries.nss
- src/utils/util_i_library.nss
Two files included in this PR.  Requirement for util_i_datapoint removed.  All libraries are run through a single sqlite table in the module's organic volatile sqlite database.
> Modified util_i_libraries and util_i_library to use sqlite table instead of datapoint

- src/chat/chat_i_main.nss
Added two functions to support your request from earlier.
`GetChatPredicate()` returns the entire portion of the chat line after the command character and command, without modification.
`GetChatTokens()` returns a comma delimited list of all the command line arguments, without dashes for options (so options and arguments cannot really be differentiated), but `key:value` pairs are maintained.
Example output:
> added GetChatPredicate() and GetChatTokens() functionality

- src/utils/util_i_debug.nss
... to prevent a bunch of color codes being printed to the game's log.  Currently condition prints color codes to the game's log when using colored strings for debug purposes.
> added string uncolor function before sending to game log

- nasher.cfg
- src/core/core_i_constants.nss
- src/core/core_i_framework.nss
- src/core/hook_nwn.nss
- src/core/hook_timerhook.nss
This change moves timers back to the sm-utils repo. To accomodate that,
CreateTimer() now executes a script when it elapses. If you want to execute an
event as before, you'll need to update timers to use CreateEventTimer() instead.
This will be merged if/when https://github.com/squattingmonk/sm-utils/pull/15 is
merged.
When merged, this will be a BREAKING CHANGE.
> refactor!: move timers from framework to utils

- src/plugins/targeting/target_l_plugin.nss
Basic plugin, much like the chat plugin, that has two targeting-specific plugins ... one for OnModuleLoad to create the targeting tables, and one for OnPlayerTarget to check if the targeting player has a global targeting hook assigned.  If a targeting hook is assigned, further scripts are not run.  I'm not sure if this is desired behavior or not.  I see it as a a benefit in most cases since the hook as an assigned script to run.  Let me know what you think of this methodology.
> Candidate plugin for `util_i_targeting` events

- src/core/core_i_framework.nss
I'm almost ashamed to say how long it took me to figure out why my AoE object framework hooking wasn't working.  Not only that, but I also made this exact same mistake when I was doing it manually to test out the issue.
> fix event script handler

- src/core/core_i_framework.nss
Fix for #45 - it's a big ugly code-scar in the function, but it works to prevent changing the behavior of a generic trigger to a transition trigger.  `GetTransitionTarget` would not work because it would return `OBJECT_INVALID` for valid transitions if the object didn't exist (yet), therefore preventing hooking the event if desired by the user.  The current method of using the json `LinkedTo` object checks to see whether a target has been set at all, even if it's invalid.  Doors may exhibit similar hard-coded behavior (auto-transition when adding an event script to `OnClicked`), but I'll have to do some testing before modifying the code for doors.
> skip trigger event for non-transition triggers

- src/core/core_c_config.nss
- src/core/core_i_framework.nss
Pretty much what the title says.  If `INSTALLED_PLUGINS` remains an empty string, any plugins discovered during library loading are automatically activated.  If plugins are specified, auto-activation does not occur and only the specified plugins are activated.
> Automatically activate discovered plugins during framework initialization

- src/demo/bw_defaultevents.uti.json
Trying this again since the other method was a waste of time given standard game methdology.
Added `nw_g0_transition:default` default script to transition-capable objects, including doors and triggers.  Also added `OnPCConversation` event to ensure pc conversation events fire correctly.
> add default transition events to bw_defaultevents.uti
